# Generated by Django 3.1.3 on 2020-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=20)),
                ('Pwd', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Pid', models.ImageField(max_length=1, upload_to='')),
                ('Token', models.TextField(max_length=30)),
                ('Token_out', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeApi',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ApiName', models.TextField()),
                ('ApiUrl', models.URLField()),
                ('ApiData', models.TextField()),
            ],
            options={
                'db_table': 'wctu_homeapi',
            },
        ),
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Keywords', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('Record', models.CharField(max_length=20)),
                ('ConInfo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserApi',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pid', models.UUIDField()),
                ('AApi', models.ImageField(max_length=10, upload_to='')),
                ('ATime', models.TextField(max_length=65535)),
                ('BApi', models.ImageField(max_length=10, upload_to='')),
                ('BTime', models.TextField(max_length=65535)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15)),
                ('UserPsaaword', models.CharField(max_length=100)),
                ('UserEmail', models.EmailField(max_length=20)),
                ('UserTel', models.CharField(blank=True, max_length=11)),
                ('UserKey', models.CharField(max_length=15)),
            ],
        ),
    ]
